#!/usr/bin/bash

ros2 service call /odrive_axis0/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis1/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis2/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis3/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis4/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis5/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis6/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis7/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis3/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis9/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis10/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"
ros2 service call /odrive_axis11/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 3}"

ros2 service call /odrive_axis0/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis1/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis2/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis3/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis4/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis5/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis6/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis7/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis8/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis9/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis10/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"
ros2 service call /odrive_axis11/request_axis_state odrive_can/srv/AxisState "{axis_requested_state: 8}"